SnmzCMS.WebAdmin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SnmzCMS.Business.Enums;
using SnmzCMS.Business.Helper;
using SnmzCMS.Business.Interface;
using SnmzCMS.Data;

namespace SnmzCMS.WebAdmin.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly IFileService _fileService;

        public ProductsController( IFileService fileService, IProductService productService, ICategoryService categoryService)
        {
            _fileService = fileService;
            _productService = productService;
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            
            var model =_productService.GetList((int) StatusEnum.Passive);
            return View(model);
        }

        public ActionResult DetailProducts(int? productId)
        {
            ViewBag.CategoryList = _categoryService.GetList((int)StatusEnum.Active);
            if (productId == null) return View();

            var model = _productService.GetById((int)productId);
            return View(model);
        }

        [HttpPost,ValidateInput(false)]
        public ActionResult DetailProducts(Products model,IEnumerable<HttpPostedFileBase> productUploadFiles)
        {
           
            var result = _productService.AddOrUpdate(model);
            ViewBag.Result = result;

            ViewBag.CategoryList = _categoryService.GetList((int)StatusEnum.Active);

            if (productUploadFiles == null) return RedirectToAction("Index");


            foreach (var files in productUploadFiles)
            {               
                if (files == null || !files.ContentType.Contains("image")) continue;

                var fileModel = UploadHelper.UploadFile(Request.PhysicalApplicationPath, ConfigurationManager.AppSettings["ImageDirectory"], files, FileTypeEnum.Photo);

                _fileService.SaveFile(fileModel);

                var productFiles = new ProductFiles
                {
                    ProductId = model.Id,
                    FileId = fileModel.Id
                };
                _productService.AddProductFiles(productFiles);
            }         
            return RedirectToAction("Index");
        }
       
    }
}

SnmzCMS.WebAdmin/Views/Products/DetailProducts.cshtml
@using SnmzCMS.Business.Enums
@using SnmzCMS.Business.Helper
@model SnmzCMS.Data.Products
<!-- Content area -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic layout-->
            @using (Html.BeginForm("DetailProducts", "Products", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h4 class="panel-title">@(Model?.Id > 0 ? "Ürün  Düzenle" : "Ürün Ekle")</h4>
                        <hr />
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li>
                                    <a data-action="collapse"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel-body">

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Kategori :</label>
                            <div class="col-lg-9">
                                @Html.DropDownListFor(model => model.CategoryId, new SelectList(ViewBag.CategoryList, "Id", "Name"), "Lütfen Seçiniz", new { @class = "form-control", @required = "required" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Sıra No :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Rank, new { @class = "form-control input-lg", placeholder = "Sıra No", required = "required" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Ürün Adı :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-lg", placeholder = "Ürün Adı", required = "required" })
                            </div>
                        </div>

                        <!-- Summernote editor -->
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Ürün Açıklaması :</label>
                            <div class="col-lg-9">
                                @Html.TextAreaFor(m => m.Description, new { @class = "form-control input-lg", placeholder = "Ürün Açıklaması" })
                            </div>
                        </div>
                        <!-- /summernote editor -->
                        <!-- Summernote editor -->
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Ürün Tablo :</label>
                            <div class="col-lg-9">
                                @Html.TextAreaFor(m => m.Detail, new { @class = "form-control input-lg", placeholder = "Ürün Tablo" })
                            </div>
                        </div>
                        <!-- /summernote editor -->


                        @if (Model?.ProductFiles != null)
                        {
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Mevcut Resimler:</label>
                                <div class="col-lg-9">
                                    @foreach (var item in Model.ProductFiles)
                                    {
                                        <img src="@MediaHelper.GetFileUrl(item.Files)" width="20%" />
                                    }
                                </div>
                            </div>
                        }

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Ürün Resmi Ekle </label>
                            <div class="col-lg-9">
                                <input type="file" accept="image/*" name="productUploadFiles" multiple="multiple" class="file-input">
                                <span class="help-block">Kabul edilen biçimler: gif, png, jpg. Maks. Dosya boyutu 2Mb</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Seo Keywords :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.SeoKeywords, new { @class = "form-control input-lg", placeholder = "Seo Keywords", required = "required" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Seo Description :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.SeoDescription, new { @class = "form-control input-lg", placeholder = "Seo Description", required = "required" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Durum :</label>
                            <div class="col-lg-9">
                                <label class="radio-inline">
                                    @if (Model != null)
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="@(Model.StatusId == (int) StatusEnum.Active)" name="StatusId"> <span> Aktif</span>
                                    }
                                    else
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="checked" name="StatusId"><span>Aktif</span>
                                    }

                                </label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn  bg-teal-700">KAYDET</button>
                        </div>
                    </div>
                </div>
            }
            <!-- /basic layout -->
        </div>
    </div>
</div>
<!-- /content area -->

<script>

    $(document).ready(function () {
        $('#Description').summernote();
        $('#Detail').summernote();
    });


</script>

SnmzCMS.WebAdmin/Views/Products/Index.cshtml
@using SnmzCMS.Business.Enums
@model List<SnmzCMS.Data.Products>

<!-- Content area -->
<div class="content">
    <!-- Main charts -->
    <div class="row">
        <div class="col-lg-12">
            <!-- Pagination types -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h4 class="panel-title">Ürün Listesi</h4>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li>
                                <a data-action="collapse"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                @if (Model.Count > 0 && Model != null)
                {
                    <div class="col-md-12">
                        <div class="text-right">
                            <a href="/createProduct" type="button" class="btn btn-info">
                                <span class="glyphicon glyphicon-plus"></span> Ekle
                            </a>
                        </div>
                        <hr />
                    </div>
                    <table class="table  datatable-responsive" id="categoryTable">
                        <thead>
                            <tr>
                                <th>Sıra No</th>
                                <th>Kategori Adı</th>
                                <th>Adı </th>
                                <th>Durum</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var product in Model)
                            {
                                <tr>
                                    <td>@product.Rank</td>
                                    <td>@product.Category.Name</td>
                                    <td>@product.Name</td>
                                    <td>@Enum.GetName(typeof(StatusEnum), product.StatusId)</td>
                                    <td>
                                        <a href="/detailProduct/@product.Id">
                                            <span class="label label-info productsEdit">
                                                <i class="fa fa-edit"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                }
                else
                {
                    <div class="row">
                        <ul class="list-inline text-center">

                            <li class="text-center">
                                <div class="text-semibold">Henüz Bir Kayıt Eklenmemiş. </div>
                            </li>

                        </ul>
                        <ul class="list-inline text-center">
                            <li>
                                <a href="/createProduct" type="button" class="btn btn-info">
                                    <span class="glyphicon glyphicon-plus"></span> Ekle
                                </a>
                            </li>
                        </ul>
                    </div>

                }

            </div>
            <!-- /pagination types -->
        </div>
    </div>
    <!-- /main charts -->
</div>
<!-- /content area -->