SnmzCMS.WebAdmin/Controllers/WebPagesController.cs
using System.Linq;
using System.Web.Mvc;
using SnmzCMS.Business.Enums;
using SnmzCMS.Business.Interface;
using SnmzCMS.Data;

namespace SnmzCMS.WebAdmin.Controllers
{
    public class WebPagesController : Controller
    {
        private readonly IWebPagesService _webPagesService;

        public WebPagesController(IWebPagesService webPagesService)
        {
            _webPagesService = webPagesService;
        }


        public ActionResult Index()
        {
            
            var model =_webPagesService.GetList((int) StatusEnum.Passive);
            return View(model);
        }

        public ActionResult DetailWebPages(int? menuId)
        {
            ViewBag.TopMenuList = _webPagesService.GetList((int) StatusEnum.Active).Where(x => x.ParentId == null);


            if (menuId == null) return View();

            var model = _webPagesService.GetById((int)menuId);
            return View(model);
        }

        [HttpPost]
        public ActionResult DetailWebPages(WebPages model)
        {            
            var result = _webPagesService.AddOrUpdate(model);
            ViewBag.Result = result;
            ViewBag.TopMenuList = _webPagesService.GetList((int)StatusEnum.Active).Where(x => x.ParentId == null);
            return RedirectToAction("Index");
        }
       
    }
}

SnmzCMS.WebAdmin/Views/WebPages/DetailWebPages.cshtml
@using SnmzCMS.Business.Enums
@using SnmzCMS.Business.Helper
@model SnmzCMS.Data.WebPages
<!-- Content area -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic layout-->
            @using (Html.BeginForm("DetailWebPages", "WebPages", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)
               
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h4 class="panel-title">@(Model?.Id > 0 ? "Menü  Düzenle" : "Menü Ekle")</h4>
                        <hr />
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li>
                                    <a data-action="collapse"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Üst Menü :</label>
                            <div class="col-lg-9">
                                @Html.DropDownListFor(model => model.ParentId, new SelectList(ViewBag.TopMenuList, "Id", "Name"), "Lütfen Seçiniz", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Menü Adı :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-lg", placeholder = "Sıra No", required = "required" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">SeoUrl :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.SeoUrl, new { @class = "form-control input-lg", placeholder = "Sıra No", @readonly = "readonly" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Sıra No :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Rank, new { @class = "form-control input-lg", placeholder = "Sıra No", required = "required" })
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Durum :</label>
                            <div class="col-lg-9">
                                <label class="radio-inline">
                                    @if (Model != null)
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="@(Model.StatusId == (int) StatusEnum.Active)" name="StatusId"><span>Aktif</span>
                                    }
                                    else
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="checked" name="StatusId"><span>Aktif</span>
                                    }

                                </label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn  bg-teal-700">KAYDET</button>
                        </div>
                    </div>
                </div>
            }
            <!-- /basic layout -->
        </div>
    </div>
</div>
<!-- /content area -->

<script>

    $("#Name").keyup(function () {
        $("#SeoUrl").val(ToSeoUrl($("#Name").val()));
    });



</script>

SnmzCMS.WebAdmin/Views/WebPages/Index.cshtml
@using SnmzCMS.Business.Enums
@model List<SnmzCMS.Data.WebPages>

<!-- Content area -->
<div class="content">
    <!-- Main charts -->
    <div class="row">
        <div class="col-lg-12">
            <!-- Pagination types -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h4 class="panel-title">Web Menü Listesi</h4>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li>
                                <a data-action="collapse"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                @if (Model.Count > 0 && Model != null)
                {
                    <div class="col-md-12">
                        <div class="text-right">
                            <a href="/createWebPage" type="button" class="btn btn-info">
                                <span class="glyphicon glyphicon-plus"></span> Ekle
                            </a>
                        </div>
                        <hr />
                    </div>

                    <table class="table  datatable-responsive" id="categoryTable">
                        <thead>
                            <tr>
                                <th>Sıra No</th>
                                <th>Menü Adı</th>
                                <th>Durum</th>
                                <th>İşlemler</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var menu in Model)
                            {
                                <tr>
                                    <td>@menu.Rank</td>
                                    <td>@menu.Name</td>
                                    <td>@Enum.GetName(typeof(StatusEnum), menu.StatusId)</td>
                                    <td>
                                        <a href="/detailWebPage/@menu.Id">
                                            <span class="label label-info productsEdit">
                                                <i class="fa fa-edit"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                }
                else
                {
                    <div class="row">
                        <ul class="list-inline text-center">

                            <li class="text-center">
                                <div class="text-semibold">Henüz Bir Kayıt Eklenmemiş. </div>
                            </li>
                        </ul>
                        <ul class="list-inline text-center">
                            <li>
                                <a href="/createWebPage" type="button" class="btn btn-info">
                                    <span class="glyphicon glyphicon-plus"></span> Ekle
                                </a>
                            </li>
                        </ul>
                    </div>

                }

            </div>
            <!-- /pagination types -->
        </div>
    </div>
    <!-- /main charts -->
</div>
<!-- /content area -->