SnmzCMS.WebAdmin/Controllers/SocialMediaController.cs
using System.Web.Mvc;
using SnmzCMS.Business.Interface;
using SnmzCMS.Data;

namespace SnmzCMS.WebAdmin.Controllers
{
    public class SocialMediaController : Controller
    {
        private readonly ISocialMediaService _socialMediaService;

        public SocialMediaController(ISocialMediaService socialMediaService)
        {
            _socialMediaService = socialMediaService;
        }


        public ActionResult Index()
        {
            var model = _socialMediaService.List();
            return View(model);
        }

        public ActionResult DetailSocialMedia(int? socialMediaId)
        {
            if (socialMediaId == null) return View();
            var model = _socialMediaService.GetById((int)socialMediaId);
            return View(model);
        }

        [HttpPost]
        public ActionResult DetailSocialMedia(SocialMedias model)
        {
            var result= _socialMediaService.AddOrUpdate(model);
            ViewBag.Result = result;
            return RedirectToAction("Index");
        }
    }
}

SnmzCMS.WebAdmin/Views/SocialMedia/DetailSocialMedia.cshtml
@using SnmzCMS.Business.Enums
@using SnmzCMS.Business.Helper
@model SnmzCMS.Data.SocialMedias
<!-- Content area -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic layout-->
            @using (Html.BeginForm("DetailSocialMedia", "SocialMedia", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h4 class="panel-title">@(Model?.Id > 0 ? "Sosyal Medya  Düzenle" : "Sosyal Medya Ekle")</h4>
                        <hr />
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li>
                                    <a data-action="collapse"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Ad :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-lg", placeholder = "Name", required = "required" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Icon Class :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.IconClass, new { @class = "form-control input-lg", placeholder = "IconClass", required = "required" })
                            </div>
                        </div>                      
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Link :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Link, new { @class = "form-control input-lg", placeholder = "Link", required = "required" })
                            </div>
                        </div>  
                       

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Durum :</label>
                            <div class="col-lg-9">
                                <label class="radio-inline">
                                    @if (Model != null)
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="@(Model.StatusId == (int)StatusEnum.Active)" name="StatusId"><span>Aktif</span>
                                    }
                                    else
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="checked" name="StatusId"><span>Aktif</span>
                                    }

                                </label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn  bg-teal-700">KAYDET</button>
                        </div>
                    </div>
                </div>
            }
            <!-- /basic layout -->
        </div>
    </div>
</div>
<!-- /content area -->

<script>

    $(window).load(function() {
        var isResult = @Html.Raw(Json.Encode(ViewBag.Result));
        if (isResult != null) {
            if (isResult.Success === true) {
                window.swal("CMS Admin", isResult.Message, "success");
            }
            else {
                window.swal("CMS Admin", isResult.Message, "error");
           }
        }

        
    });



</script>

SnmzCMS.WebAdmin/Views/SocialMedia/Index.cshtml
@using SnmzCMS.Business.Enums
@model List<SnmzCMS.Data.SocialMedias>

<!-- Content area -->
<div class="content">
    <!-- Main charts -->
    <div class="row">
        <div class="col-lg-12">
            <!-- Pagination types -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h4 class="panel-title">Sosyal Medya Listesi</h4>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li>
                                <a data-action="collapse"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                @if (Model.Count > 0 && Model != null)
                {
                <div class="col-md-12">
                    <div class="text-right">
                        <a href="/createSocialMedia" type="button" class="btn btn-info">
                            <span class="glyphicon glyphicon-plus"></span> Ekle
                        </a>
                    </div>
                    <hr />
                </div>

                    <table class="table  datatable-responsive" >
                        <thead>
                            <tr>
                                <th>Adı</th>
                                <th>Link</th>
                                <th>Durum</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var social in Model)
                            {
                                <tr>
                                    <td>@social.Name</td>
                                    <td>@social.Link</td>
                                    <td>@Enum.GetName(typeof(StatusEnum), social.StatusId)</td>
                                    <td>
                                        <a href="/DetailSocialMedia/@social.Id">
                                            <span class="label label-info productsEdit">
                                                <i class="fa fa-edit"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                }
                else
                {

                    <div class="row">
                        <ul class="list-inline text-center">

                            <li class="text-center">
                                <div class="text-semibold">Henüz Bir Kayıt Eklenmemiş. </div>
                            </li>

                        </ul>
                        <ul class="list-inline text-center">
                            <li>
                                <a href="/createSocialMedia" type="button" class="btn btn-info">
                                    <span class="glyphicon glyphicon-plus"></span> Ekle
                                </a>
                            </li>
                        </ul>
                    </div>

                }

            </div>
            <!-- /pagination types -->
        </div>
    </div>
    <!-- /main charts -->
</div>
<!-- /content area -->