SnmzCMS.WebAdmin/Controllers/ContentPagesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SnmzCMS.Business.Enums;
using SnmzCMS.Business.Helper;
using SnmzCMS.Business.Interface;
using SnmzCMS.Data;

namespace SnmzCMS.WebAdmin.Controllers
{
    public class ContentPagesController : Controller
    {
        private readonly IContentPagesService _contentPagesService;
        private readonly IWebPagesService _webPagesService;
        private readonly IGalleryService _galleryService;
        private readonly IFileService _fileService;

        public ContentPagesController(IContentPagesService contentPagesService,IWebPagesService webPagesService, IGalleryService galleryService, IFileService fileService)
        {
            _contentPagesService = contentPagesService;
            _webPagesService = webPagesService;
            _galleryService = galleryService;
            _fileService = fileService;
        }

        public ActionResult Index()
        {
            var model =_contentPagesService.GetList((int) StatusEnum.Passive);
            return View(model);
        }

        public ActionResult DetailContentPage(int? contentId)
        {
            ViewBag.WebPages = _webPagesService.GetList((int)StatusEnum.Active);
            ViewBag.Gallery = _galleryService.GetList((int)StatusEnum.Active);
            if (contentId == null) return View();
            var model = _contentPagesService.GetById((int)contentId);           
            return View(model);
        }

        [HttpPost,ValidateInput(false)]
        public ActionResult DetailContentPage(ContentPages model, HttpPostedFileBase contentUploadFile)
        {

            if (contentUploadFile != null && contentUploadFile.ContentType.Contains("image"))
            {

                var fileModel = UploadHelper.UploadFile(Request.PhysicalApplicationPath, ConfigurationManager.AppSettings["ImageDirectory"], contentUploadFile, FileTypeEnum.Photo);

                _fileService.SaveFile(fileModel);
                model.FileId = fileModel.Id;
            }

            var result= _contentPagesService.AddOrUpdate(model);
            ViewBag.Result = result;
            ViewBag.WebPages = _webPagesService.GetList((int) StatusEnum.Active);
            ViewBag.Gallery = _galleryService.GetList((int) StatusEnum.Active);
                
            return RedirectToAction("Index");
        }
    }
}

SnmzCMS.WebAdmin/Views/ContentPages/DetailContentPage.cshtml
@using SnmzCMS.Business.Enums
@using SnmzCMS.Business.Helper
@model SnmzCMS.Data.ContentPages
<!-- Content area -->
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Basic layout-->
            @using (Html.BeginForm("DetailContentPage", "ContentPages", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.Id)
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h4 class="panel-title">@(Model?.Id > 0 ? "İçerik  Düzenle" : "İçerik Ekle")</h4>
                        <hr />
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li>
                                    <a data-action="collapse"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Başlık :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.Title, new { @class = "form-control input-lg", placeholder = "Başlık", required = "required" })
                            </div>
                        </div>

                        <!-- Summernote editor -->
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Açıklama :</label>
                            <div class="col-lg-9">
                                @Html.TextAreaFor(m => m.Description, new { @class = "form-control input-lg", placeholder = "İçerik Açıklaması" })
                            </div>
                        </div>
                        <!-- /summernote editor -->

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Sayfa :</label>
                            <div class="col-lg-9">
                                @Html.DropDownListFor(model => model.SeoUrl, new SelectList(ViewBag.WebPages, "SeoUrl", "Name"), "Lütfen Seçiniz", new { @class = "form-control", @required = "required" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Galeri :</label>
                            <div class="col-lg-9">
                                @Html.DropDownListFor(model => model.GalleryId, new SelectList(ViewBag.Gallery, "Id", "Name"), "Lütfen Seçiniz", new { @class = "form-control" })
                            </div>
                        </div>

                        @if (Model?.Files != null)
                        {
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Mevcut Resimler:</label>
                                <div class="col-lg-9">
                                    <img src="@MediaHelper.GetFileUrl(Model.Files)" width="20%" />
                                </div>
                            </div>
                        }

                        <div class="form-group">
                            <label class="col-lg-3 control-label">İçerik Resmi Ekle </label>
                            <div class="col-lg-9">
                                <input type="file" accept="image/*" name="contentUploadFile" class="file-input">
                                <span class="help-block">Kabul edilen biçimler: gif, png, jpg. Maks. Dosya boyutu 2Mb</span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Seo Description :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.SeoDescription, new { @class = "form-control input-lg", placeholder = "Seo Description" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Seo Keywords :</label>
                            <div class="col-lg-9">
                                @Html.TextBoxFor(m => m.SeoKeywords, new { @class = "form-control input-lg", placeholder = "Seo Keywords" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Durum :</label>
                            <div class="col-lg-9">
                                <label class="radio-inline">
                                    @if (Model != null)
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="@(Model.StatusId == (int) StatusEnum.Active)" name="StatusId"> <span> Aktif</span>
                                    }
                                    else
                                    {
                                        <input type="checkbox" class="styled" value="1" checked="checked" name="StatusId"><span>Aktif</span>
                                    }

                                </label>
                            </div>
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn  bg-teal-700">KAYDET</button>
                        </div>
                    </div>
                </div>
            }
            <!-- /basic layout -->
        </div>
    </div>
</div>
<!-- /content area -->
<script>

    $(document).ready(function () {
        $('#Description').summernote();
    });


</script>

SnmzCMS.WebAdmin/Views/ContentPages/Index.cshtml
@using SnmzCMS.Business.Enums
@model List<SnmzCMS.Data.ContentPages>

<!-- Content area -->
<div class="content">
    <!-- Main charts -->
    <div class="row">
        <div class="col-lg-12">
            <!-- Pagination types -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h4 class="panel-title">İçerik Listesi</h4>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li>
                                <a data-action="collapse"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                @if (Model.Count > 0 && Model != null)
                {
                <div class="col-md-12">
                    <div class="text-right">
                        <a href="/createContentPage" type="button" class="btn btn-info">
                            <span class="glyphicon glyphicon-plus"></span> Ekle
                        </a>
                    </div>
                    <hr />
                </div>

                    <table class="table  datatable-responsive" id="categoryTable">
                        <thead>
                            <tr>
                                <th>İçerik Başlığı</th>
                                <th>Durum</th>
                                <th>İşlemler</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var content in Model)
                            {
                                <tr>
                                    <td>@content.Title</td>
                                    <td>@Enum.GetName(typeof(StatusEnum), content.StatusId)</td>
                                    <td>
                                        <a href="/detailContentPage/@content.Id">
                                            <span class="label label-info productsEdit">
                                                <i class="fa fa-edit"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                }
                else
                {
                    <div class="row">
                        <ul class="list-inline text-center">

                            <li class="text-center">
                                <div class="text-semibold">Henüz Bir Kayıt Eklenmemiş. </div>
                            </li>

                        </ul>
                        <ul class="list-inline text-center">
                            <li>
                                <a href="/createContentPage" type="button" class="btn btn-info">
                                    <span class="glyphicon glyphicon-plus"></span> Ekle
                                </a>
                            </li>
                        </ul>
                    </div>

                }

            </div>
            <!-- /pagination types -->
        </div>
    </div>
    <!-- /main charts -->
</div>
<!-- /content area -->